name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build dockerfile
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Run a multi-line script
      run: |
        IMAGE_NAME=test_container:$(date +%s)
        docker build ./app --tag docker.pkg.github.com/k8shiro/github_docker_push_example/${IMAGE_NAME}
        docker login docker.pkg.github.com --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
        docker push docker.pkg.github.com/k8shiro/github_docker_push_example/${IMAGE_NAME}
      env:
          DOCKER_USERNAME: ${{ secrets.GITHUB_DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_DOCKER_PASSWORD }}
